// Q4: Write a program to convert Celsius to Fahrenheit .
// i.e: Temperature in degrees Fahrenheit (°F) = (Temperature in degrees Celsius
// (°C) * 9/5) + 32


void main(){
print("YASIR FAHEEM");
print("Assingment no 1");
print("Q4: Write a program to convert Celsius to Fahrenheit .\n i.e: Temperature in degrees Fahrenheit (°F) = (Temperature in degrees Celsius \n (°C) * 9/5) + 32");

print("Answer\n");
num temp_celsius = 30;

num temp_fahrenheit= (temp_celsius*(9/5)+32);
print(temp_fahrenheit);

}



