// Q.3: A student will not be allowed to sit in exam if his/her attendance is less
// than 75%. Create integer variables and assign value:
// Number of classes held = 16,
// Number of classes attended = 10,
// and print percentage of class attended.
// Is student is allowed to sit in exam or not?
void main(){
print("YASIR FAHEEM");
print("Assingment no 1");
print("Q.3: A student will not be allowed to sit in exam if his/her attendance is less \n than 75%. Create integer variables and assign value: \n Number of classes held = 16, /n Number of classes attended = 10, /n and print percentage of class attended. \nIs student is allowed to sit in exam or not?");


int classes_held = 16;
int attend_class =10;

num percentage;

percentage= (10/16)*100;

print("$percentage%");

if(percentage>=75)
{
  print("you are allowed in exam");
}
else{
  print("you are not allowed in exam");
}



}



