// question no 2 Take two variables and store age then using if/else condition to determine
// oldest and youngest among them.

void main(){
print("YASIR FAHEEM");
print("Assingment no 1");
print("Q2 :Take two variables and store age then using if/else condition to determine \n oldest and youngest among them.");
 int age1 = 18;
 //age1 is for young man
 int age2 = 40;
//age2 is for old man
if (age1<=age2){
  print(" age1 you are young man");
}
else{
  print ("you are old man");
}
}