

// Q.1: Create two integer variables length and breadth and assign values then
// check if they are square values or rectangle values.
// ie: if both values are equal then it's square otherwise rectangle.

void main(){
print("YASIR FAHEEM");
print("Assingment no 1");
print("Q.1: Create two integer variables length and breadth and assign values then \n check if they are square values or rectangle values.\n ie: if both values are equal then it's square otherwise rectangle.");
num length = 21;
num breath= 21;

if(breath==length){
    print("Answer is :   its square");
}
else{
    print("Answer is :    its rectangle");
}

}