// Q.6: Write a program to check whether an alphabet is a vowel or consonant.

void main(){
print("YASIR FAHEEM");
print("Assingment no 1");
print("Q.6: Write a program to check whether an alphabet is a vowel or consonant.");

print("Answer\n");

String alphabet="b";

if(alphabet=="a" || alphabet=="e"|| alphabet=="i" || alphabet=="o" || alphabet=="u" ){
print("the $alphabet is vowels");
}
else{
  print("the $alphabet is consonants");
}


}

